[package]
edition = "2018"
name = "ecs_engine"
version = "0.1.0"
authors = ["silverweed <silverweed1991@gmail.com>"]

[features]
use-sfml = ["sfml"]
default = ["use-sfml"]

[dependencies]
lazy_static = "1.3.0"
notify = "4.0"
bitflags = "1.1.0"
num_enum = "0.3.1"
byteorder = "1.3.2"
crossbeam = "0.7"
num_cpus = "*"

[dependencies.cgmath]
git = "https://github.com/rustgd/cgmath"
rev = "50a345b"

[dependencies.sfml]
version = "0.15.1"
optional = true
features = ["graphics", "audio"]

[dev-dependencies]
float-cmp = "0.5.2"
