[package]
edition = "2018"
name = "ecs_engine"
version = "0.1.0"
authors = ["silverweed <silverweed1991@gmail.com>"]

[features]
use-sfml = ["sfml"]
default = ["use-sfml"]

[dependencies]
bitflags = "1.1.0"
num_enum = "0.3.1"
byteorder = "1.3.2"
rayon = "1.3"
anymap = "0.12"

# debug-only deps
notify = "4.0"
lazy_static = "1.3.0"

[target.'cfg(not(target_os = "windows"))'.dependencies]
libc = "0.2"

[dependencies.cgmath]
git = "https://github.com/rustgd/cgmath"
rev = "50a345b"

[dependencies.sfml]
version = "0.15.1"
git = "https://github.com/jeremyletang/rust-sfml"
rev = "f3bc9e73"
optional = true
features = ["graphics", "audio"]

[dev-dependencies]
float-cmp = "0.5.2"
