[package]
edition = "2018"
name = "ecs_engine"
version = "0.1.0"
authors = ["silverweed <silverweed1991@gmail.com>"]

[features]
use-sfml = ["sfml"]
gfx-null = []
gfx-sfml = ["sfml/graphics"]
default = ["use-sfml", "gfx-sfml"]

[dependencies]
byteorder = "1.3.2"
rayon = "1.3"
anymap = "0.12"

# debug-only deps
notify = "4.0"
lazy_static = "1.3.0"

[target.'cfg(not(target_os = "windows"))'.dependencies]
libc = "0.2"

[dependencies.sfml]
version = "0.15.1"
#git = "https://github.com/jeremyletang/rust-sfml"
#rev = "f3bc9e73"
path = "../../rust-sfml"
optional = true
default-features = false
features = ["audio", "window", "graphics"]

[dev-dependencies]
float-cmp = "0.5.2"
