[package]
edition = "2018"
name = "ecs_game"
version = "0.1.0"
authors = ["silverweed <silverweed1991@gmail.com>"]

[lib]
crate-type = ["dylib"]

[dependencies]
anymap = "0.12.1"
typename = "0.1.1"
cgmath = "0.17.0"

[dependencies.ecs_engine]
features = ["use-sfml"]
path = "../ecs_engine"
