[package]
edition = "2018"
name = "ecs"
version = "0.1.0"
authors = ["silverweed <silverweed1991@gmail.com>"]

[features]
hotload = ["notify"]
#default = ["hotload"]
default = []

[dependencies]
libloading = "0.5"

[dependencies.notify]
optional = true
version = "4.0"

