[package]
edition = "2018"
name = "ecs"
version = "0.1.0"
authors = ["silverweed <silverweed1991@gmail.com>"]

[dependencies]
libloading = "0.5"

[target.'cfg(debug_assertions)'.dependencies]
notify = "4.0"

