[package]
edition = "2021"
name = "inle_runner"
version = "0.1.0"
authors = ["silverweed <silverweed1991@gmail.com>"]

[features]
hotload = ["notify"]
default = ["hotload"]
#default = []

[dependencies]
libloading = "0.8"

[dependencies.notify]
optional = true
version = "4.0"
